# Generated by Django 4.2.27 on 2025-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_verified_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preference",
            options={
                "ordering": ["category", "id"],
                "verbose_name": "Préférence",
                "verbose_name_plural": "Préférences",
            },
        ),
        migrations.AddField(
            model_name="preference",
            name="category",
            field=models.CharField(
                choices=[
                    ("interests", "Centres d'intérêt"),
                    ("habits", "Habitudes"),
                    ("driving", "Préférences de conduite"),
                ],
                default="interests",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="icon",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="preference",
            name="name_en",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="preference",
            name="name_fr",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
