# final_fix.ps1 - Solution finale
Write-Host "🔧 Correction finale des migrations" -ForegroundColor Cyan

# 1. Nettoyer les anciennes migrations 0007+
Write-Host "`n📌 Nettoyage..." -ForegroundColor Yellow
Get-ChildItem "app\trajets\migrations" -Filter "000[789]_*.py" | ForEach-Object {
    Write-Host "Suppression de $($_.Name)" -ForegroundColor Gray
    Remove-Item $_.FullName
}

# 2. Créer la migration finale
Write-Host "`n📌 Création de la migration 0007..." -ForegroundColor Yellow

$migrationContent = @'
# Generated by final fix script

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0006_delete_trajetpreference'),
        ('users', '0003_alter_preference_options_preference_category_and_more'),
    ]

    operations = [
        # Créer TrajetPreference
        migrations.CreateModel(
            name='TrajetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajet_preferences', to='trajets.trajet')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_trajets', to='users.preference')),
            ],
            options={
                'db_table': 'trajets_preferences',
            },
        ),
        
        # Contrainte unique
        migrations.AlterUniqueTogether(
            name='trajetpreference',
            unique_together={('trajet', 'preference')},
        ),
        
        # Index
        migrations.AddIndex(
            model_name='trajetpreference',
            index=models.Index(fields=['trajet'], name='trajets_pre_trajet_idx'),
        ),
        migrations.AddIndex(
            model_name='trajetpreference',
            index=models.Index(fields=['preference'], name='trajets_pre_pref_idx'),
        ),
        
        # Ajouter le champ preferences
        migrations.AddField(
            model_name='trajet',
            name='preferences',
            field=models.ManyToManyField(
                blank=True,
                help_text='Préférences du conducteur pour ce trajet',
                related_name='trajets',
                through='trajets.TrajetPreference',
                to='users.preference',
            ),
        ),
    ]
'@

$migrationFile = "app\trajets\migrations\0007_trajetpreference_trajet_preferences.py"
Set-Content -Path $migrationFile -Value $migrationContent
Write-Host "✅ Fichier créé: $migrationFile" -ForegroundColor Green

# 3. Appliquer la migration
Write-Host "`n📌 Application de la migration..." -ForegroundColor Yellow
python manage.py migrate trajets

# 4. Vérification
Write-Host "`n📌 Vérification de l'état..." -ForegroundColor Yellow
python manage.py showmigrations trajets

Write-Host "`n✅ TERMINÉ!" -ForegroundColor Green
Write-Host "Testez maintenant votre recherche intelligente" -ForegroundColor Cyan