# Generated by Django 4.2.27 on 2025-12-31 20:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville_depart", models.CharField(max_length=100)),
                ("ville_arrivee", models.CharField(max_length=100)),
                ("adresse_depart", models.TextField(blank=True)),
                ("adresse_arrivee", models.TextField(blank=True)),
                ("date", models.DateField(db_index=True)),
                ("heure_depart", models.TimeField()),
                (
                    "nbr_places",
                    models.IntegerField(
                        help_text="Nombre total de places disponibles",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "places_disponibles",
                    models.IntegerField(
                        help_text="Nombre de places encore disponibles",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix par siège fixé par le conducteur",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "price_platform",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commission de la plateforme (15%)",
                        max_digits=10,
                    ),
                ),
                (
                    "price_driver",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant net reversé au conducteur",
                        max_digits=10,
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix conseillé basé sur le coût du carburant (cahier des charges)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance du trajet en km",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "is_confort",
                    models.BooleanField(
                        default=False, help_text="Option Trajet Confort (+30%)"
                    ),
                ),
                (
                    "pause_required",
                    models.BooleanField(
                        default=False,
                        help_text="Pause obligatoire pour trajets > 300km",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("essence_sans_plomb", "Essence Sans Plomb"),
                            ("gasoil", "Gasoil"),
                            ("gpl", "GPL"),
                            ("electrique", "Électrique"),
                        ],
                        default="gasoil",
                        help_text="Type de carburant utilisé par le véhicule",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        help_text="Consommation du véhicule (L/100km ou kWh/100km pour électrique)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "wilaya_depart",
                    models.CharField(
                        blank=True,
                        help_text="Wilaya de départ extraite automatiquement de l'adresse",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("COMPLETED", "Terminé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                ("luggage_allowed", models.BooleanField(default=True)),
                (
                    "conducteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajets_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trajet",
                "verbose_name_plural": "Trajets",
                "db_table": "trajets",
                "ordering": ["-date", "-heure_depart"],
            },
        ),
        migrations.CreateModel(
            name="TrajetPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference_trajets",
                        to="users.preference",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajet_preferences",
                        to="trajets.trajet",
                    ),
                ),
            ],
            options={
                "db_table": "trajets_preferences",
            },
        ),
        migrations.CreateModel(
            name="TrajetEtape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(max_length=100)),
                ("adresse", models.TextField(blank=True)),
                ("heure_arrivee", models.TimeField()),
                (
                    "ordre",
                    models.IntegerField(
                        help_text="Ordre de l'étape dans le trajet",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="trajets.trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de Trajet",
                "verbose_name_plural": "Étapes de Trajet",
                "db_table": "trajet_etapes",
                "ordering": ["ordre"],
            },
        ),
        migrations.AddField(
            model_name="trajet",
            name="preferences",
            field=models.ManyToManyField(
                blank=True,
                help_text="Préférences du conducteur pour ce trajet",
                related_name="trajets",
                through="trajets.TrajetPreference",
                to="users.preference",
            ),
        ),
        migrations.CreateModel(
            name="FuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wilaya_code",
                    models.CharField(db_index=True, default="", max_length=2),
                ),
                ("wilaya_name", models.CharField(default="", max_length=100)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("essence_sans_plomb", "Essence Sans Plomb"),
                            ("gasoil", "Gasoil"),
                            ("gpl", "GPL"),
                            ("electrique", "Électrique"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_liter",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("effective_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prix Carburant",
                "verbose_name_plural": "Prix Carburants",
                "db_table": "fuel_prices",
                "ordering": ["-effective_date", "wilaya_name"],
                "indexes": [
                    models.Index(
                        fields=["wilaya_name", "fuel_type"],
                        name="fuel_prices_wilaya__296c19_idx",
                    )
                ],
                "unique_together": {("wilaya_code", "fuel_type", "effective_date")},
            },
        ),
        migrations.AddIndex(
            model_name="trajetpreference",
            index=models.Index(
                fields=["trajet"], name="trajets_pre_trajet__53f2a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trajetpreference",
            index=models.Index(
                fields=["preference"], name="trajets_pre_prefere_4c7b35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trajetpreference",
            unique_together={("trajet", "preference")},
        ),
        migrations.AlterUniqueTogether(
            name="trajetetape",
            unique_together={("trajet", "ordre")},
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["ville_depart", "ville_arrivee", "date"],
                name="trajets_ville_d_7e762b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["conducteur", "status"], name="trajets_conduct_a7be64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["date", "status"], name="trajets_date_6f7f39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(fields=["fuel_type"], name="trajets_fuel_ty_43b2dc_idx"),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["wilaya_depart"], name="trajets_wilaya__311600_idx"
            ),
        ),
    ]
