# Generated by Django 4.2.27 on 2025-12-14 17:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wilaya", models.CharField(db_index=True, max_length=100)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("ESSENCE", "Essence"), ("DIESEL", "Diesel")],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_liter",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("effective_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prix Carburant",
                "verbose_name_plural": "Prix Carburants",
                "db_table": "fuel_prices",
                "ordering": ["-effective_date", "wilaya"],
            },
        ),
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville_depart", models.CharField(max_length=100)),
                ("ville_arrivee", models.CharField(max_length=100)),
                ("adresse_depart", models.TextField(blank=True)),
                ("adresse_arrivee", models.TextField(blank=True)),
                ("date", models.DateField(db_index=True)),
                ("heure_depart", models.TimeField()),
                (
                    "nbr_places",
                    models.IntegerField(
                        help_text="Nombre total de places disponibles",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "places_disponibles",
                    models.IntegerField(
                        help_text="Nombre de places encore disponibles",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix par siège fixé par le conducteur",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "price_platform",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commission de la plateforme (15%)",
                        max_digits=10,
                    ),
                ),
                (
                    "price_driver",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant net reversé au conducteur",
                        max_digits=10,
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix conseillé basé sur le coût du carburant",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance du trajet en km",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "is_confort",
                    models.BooleanField(
                        default=False, help_text="Option Trajet Confort (+30%)"
                    ),
                ),
                (
                    "pause_required",
                    models.BooleanField(
                        default=False,
                        help_text="Pause obligatoire pour trajets > 300km",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("COMPLETED", "Terminé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                ("luggage_allowed", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Trajet",
                "verbose_name_plural": "Trajets",
                "db_table": "trajets",
                "ordering": ["-date", "-heure_depart"],
            },
        ),
        migrations.CreateModel(
            name="TrajetEtape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(max_length=100)),
                ("adresse", models.TextField(blank=True)),
                ("heure_arrivee", models.TimeField()),
                (
                    "ordre",
                    models.IntegerField(
                        help_text="Ordre de l'étape dans le trajet",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="trajets.trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de Trajet",
                "verbose_name_plural": "Étapes de Trajet",
                "db_table": "trajet_etapes",
                "ordering": ["ordre"],
            },
        ),
    ]
