# Generated by Django 4.2.27 on 2025-12-14 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trajets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trajet",
            name="conducteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trajets_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fuelprice",
            unique_together={("wilaya", "fuel_type", "effective_date")},
        ),
        migrations.AlterUniqueTogether(
            name="trajetetape",
            unique_together={("trajet", "ordre")},
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["ville_depart", "ville_arrivee", "date"],
                name="trajets_ville_d_7e762b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["conducteur", "status"], name="trajets_conduct_a7be64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["date", "status"], name="trajets_date_6f7f39_idx"
            ),
        ),
    ]
