# Generated by Django 4.2.27 on 2025-12-22 11:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_preference_options_preference_category_and_more"),
        ("trajets", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrajetPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "trajets_preferences",
            },
        ),
        migrations.AlterModelOptions(
            name="fuelprice",
            options={
                "ordering": ["-effective_date", "wilaya_name"],
                "verbose_name": "Prix Carburant",
                "verbose_name_plural": "Prix Carburants",
            },
        ),
        migrations.AlterUniqueTogether(
            name="fuelprice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fuelprice",
            name="wilaya_code",
            field=models.CharField(db_index=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="fuelprice",
            name="wilaya_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="trajet",
            name="fuel_consumption",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8.00"),
                help_text="Consommation du véhicule (L/100km ou kWh/100km pour électrique) - défaut 8L/100km",
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="trajet",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("essence_sans_plomb", "Essence Sans Plomb"),
                    ("gasoil", "Gasoil"),
                    ("gpl", "GPL"),
                    ("electrique", "Électrique"),
                ],
                default="gasoil",
                help_text="Type de carburant utilisé par le véhicule",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trajet",
            name="music_allowed",
            field=models.BooleanField(
                default=True, help_text="Musique autorisée pendant le trajet"
            ),
        ),
        migrations.AddField(
            model_name="trajet",
            name="no_smoking",
            field=models.BooleanField(default=True, help_text="Véhicule non-fumeur"),
        ),
        migrations.AddField(
            model_name="trajet",
            name="small_luggage_only",
            field=models.BooleanField(
                default=False, help_text="Uniquement petits bagages acceptés"
            ),
        ),
        migrations.AddField(
            model_name="trajet",
            name="wilaya_depart",
            field=models.CharField(
                blank=True,
                help_text="Wilaya de départ extraite automatiquement de l'adresse",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fuelprice",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("essence_sans_plomb", "Essence Sans Plomb"),
                    ("gasoil", "Gasoil"),
                    ("gpl", "GPL"),
                    ("electrique", "Électrique"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trajet",
            name="suggested_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix conseillé basé sur le coût du carburant (cahier des charges)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fuelprice",
            unique_together={("wilaya_code", "fuel_type", "effective_date")},
        ),
        migrations.AddIndex(
            model_name="fuelprice",
            index=models.Index(
                fields=["wilaya_name", "fuel_type"],
                name="fuel_prices_wilaya__296c19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(fields=["fuel_type"], name="trajets_fuel_ty_43b2dc_idx"),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["wilaya_depart"], name="trajets_wilaya__311600_idx"
            ),
        ),
        migrations.AddField(
            model_name="trajetpreference",
            name="preference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference_trajets",
                to="users.preference",
            ),
        ),
        migrations.AddField(
            model_name="trajetpreference",
            name="trajet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trajet_preferences",
                to="trajets.trajet",
            ),
        ),
        migrations.RemoveField(
            model_name="fuelprice",
            name="wilaya",
        ),
        migrations.AddIndex(
            model_name="trajetpreference",
            index=models.Index(
                fields=["trajet"], name="trajets_pre_trajet__53f2a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trajetpreference",
            index=models.Index(
                fields=["preference"], name="trajets_pre_prefere_4c7b35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trajetpreference",
            unique_together={("trajet", "preference")},
        ),
    ]
