# Generated by Django 4.2.27 on 2025-12-22 15:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_preference_options_preference_category_and_more"),
        ("trajets", "0003_trajetpreference_alter_fuelprice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trajet",
            name="preferences",
            field=models.ManyToManyField(
                blank=True,
                help_text="Préférences du conducteur pour ce trajet",
                related_name="trajets",
                through="trajets.TrajetPreference",
                to="users.preference",
            ),
        ),
        migrations.AlterField(
            model_name="trajet",
            name="fuel_consumption",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8.00"),
                help_text="Consommation du véhicule (L/100km ou kWh/100km pour électrique)",
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
