# Generated by Django 4.2.27 on 2025-12-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trajets", "0005_clean_preferences"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrajetPreference",
        ),
    ]
