# Generated by Django 4.2.27 on 2025-12-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trajets", "0007_trajetpreference_trajet_preferences"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="trajetpreference",
            new_name="trajets_pre_trajet__53f2a7_idx",
            old_name="trajets_pre_trajet_idx",
        ),
        migrations.RenameIndex(
            model_name="trajetpreference",
            new_name="trajets_pre_prefere_4c7b35_idx",
            old_name="trajets_pre_pref_idx",
        ),
    ]
