# Generated by Django 4.2.27 on 2025-12-14 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "conversations",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="messages/media/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                ("media_type", models.CharField(blank=True, max_length=50)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messagerie",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RESERVATION_REQUEST", "Demande de réservation"),
                            ("RESERVATION_APPROVED", "Réservation approuvée"),
                            ("RESERVATION_REJECTED", "Réservation rejetée"),
                            ("RESERVATION_CANCELLED", "Réservation annulée"),
                            ("MESSAGE_RECEIVED", "Message reçu"),
                            ("TRAJET_CANCELLED", "Trajet annulé"),
                            ("TRAJET_MODIFIED", "Trajet modifié"),
                            ("RATING_RECEIVED", "Évaluation reçue"),
                            ("DOCUMENT_VERIFIED", "Document vérifié"),
                            ("DOCUMENT_REJECTED", "Document rejeté"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("related_model", models.CharField(blank=True, max_length=50)),
                ("related_id", models.IntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
