# Generated by Django 4.2.27 on 2026-01-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
