# Generated by Django 4.2.27 on 2025-12-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "trajets",
            "0008_rename_trajets_pre_trajet_idx_trajets_pre_trajet__53f2a7_idx_and_more",
        ),
        (
            "notifications",
            "0003_conversation_is_group_message_is_group_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="notifications.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="trajet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="trajets.trajet",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("RESERVATION_REQUEST", "Demande de réservation"),
                    ("RESERVATION_APPROVED", "Réservation approuvée"),
                    ("RESERVATION_REJECTED", "Réservation rejetée"),
                    ("RESERVATION_CANCELLED", "Réservation annulée"),
                    ("MESSAGE_RECEIVED", "Message reçu"),
                    ("TRAJET_CANCELLED", "Trajet annulé"),
                    ("TRAJET_MODIFIED", "Trajet modifié"),
                    ("RATING_RECEIVED", "Évaluation reçue"),
                    ("DOCUMENT_VERIFIED", "Document vérifié"),
                    ("DOCUMENT_REJECTED", "Document rejeté"),
                    ("WELCOME", "Bienvenue"),
                ],
                max_length=50,
            ),
        ),
    ]
